# -*- coding: utf-8 -*-
"""matplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNdqKu4fO7sUnLOjt-PDyJAWe57ryfDF
"""

import numpy as np
import matplotlib.pyplot as plt
runs = np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(w,runs,color='red',label='srh')
plt.legend(loc='best')
plt.title('srhvscsk_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
tigar = np.linspace(-2*np.pi, 2*np.pi, 100)
print(tigar)
plt.plot(tigar, np.sin(tigar) ,color='pink',linestyle='dotted')
plt.title("sin(x)")
plt.legend(loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)

runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color='orange',label='srh')
plt.plot(overs_a,runs_a,color='yellow',label = 'csk')
#combining two graphs
plt.legend(loc='best')
#displaying the final graph
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '10',linestyle='dotted',label ='CompanyA',marker='.',ms='20',mec='r')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label ='CompanyB',marker = 'H')
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
color = ['green','red','pink','yellow']
plt.pie(a,labels = labe,colors= color)


plt.show()

a = np.array([25,60,5,10])
labe = ["CSE","Python","Pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels = labe,explode = explo,startangle = 90)
plt.show()

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.scatterplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("scatter plot of sepal_length vs. sepal_width")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.barplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("scatter plot of sepal_length vs. sepal_width")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.boxplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("scatter plot of sepal_length vs. sepal_width")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.barplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of total bill vs. tip")
plt.xlabel("total bill($)")
plt.ylabel("tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.violinplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("scatter plot of sepal_length vs. sepal_width")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width($)")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
a=pd.read_csv("/grades_withnulls.csv")
b=sns.lineplot(x='Names',y='Grade',data=a)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlation heatmap of iris dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.jointplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of total bill vs. tip")
plt.xlabel("total bill($)")
plt.ylabel("tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.countplot(x="total_bill",data=tips)
plt.title("scatter plot of total bill vs. tip")
plt.xlabel("total bill($)")
plt.ylabel("tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.lmplot(x="total_bill",y="tip",data=tips)
plt.title(" linear plot of total bill vs. tip")
plt.xlabel("total bill($)")
plt.ylabel("tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
titanic= sns.load_dataset("titanic")
print(titanic)
#create a count plot
#Create a facet grid of age distributions for different passeng
g = sns.FacetGrid(titanic, col="class")

g.map(sns.histplot, "age")

plt.subplots_adjust(top=0.8)

g.fig.suptitle("Age Distribution by Passenger Class")

plt.show()

