# -*- coding: utf-8 -*-
"""NumPY DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1liasmsT_uFFFRN2iYdKe5ca2GhIDh7CK
"""

import numpy as np
arr=np.array([1,2,3,4,5,6],dtype=float)
print(arr)

zarr=np.zeros((3,3),dtype=float)
print(zarr)
oarr=np.ones((2,2),dtype=int)
print(oarr)
arrange=np.arange(1,10)
print(arrange)

reshaped=arr.reshape(6,1)
print(reshaped)

sliced=arr[1:6]
print(sliced)

a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)

b=np.split(a,4)
print(b)

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

import numpy as np
data = np.loadtxt("/content/drive/MyDrive/colab/DAP1.txt")
d=np.savetxt("/content/data.txt",data)
print(d)
print(data)

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import random
arrange=np.arange(0,100,5)
print(arrange)
d=np.savetxt("/content/drive/MyDrive/colab/arr.txt",arrange)

a=np.random.rand()
print (a)
np.random.randint(2,19)

a=np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.shape)

a=np.linspace(0.8,2,5)
print(a)

arrange=np.arange(24).reshape(2,3,4)
print(arrange)

arrange=np.arange(4).reshape(2,2)
arrange1=np.arange(4).reshape(2,2)
print(arrange1*arrange)
print(arrange1@arrange)
print(np.dot(arrange1,arrange))

from numpy import random
a=np.ones([2,3],dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=0))
a=np.floor(np.random.random((2,12)))
print(a)
c=np.random.random((2,2))
print(c)
a1=np.ceil(np.random.random((2,12)))
print(a1)

from numpy import random
a=np.arange(4).reshape(2,2)
a1=np.arange(4).reshape(2,2)
print(a)
print(a.sum())
print(a.max(axis=1))
print(a.min(axis=1))

from numpy import random
a=np.arange(4).reshape(2,2)
a1=np.arange(4).reshape(2,2)


print(a1.cumsum(axis=1))
print(a.cumsum(axis=0))

a=np.array([1,2,3,3,5,4])
print(a.cumsum())

a=np.array([1,2,3,3,5,4])
a.resize(3,2)
print(a)

a=np.array([1,2,3,3,5,4])
a.resize(2,3)
b=np.array([11,22,3,3,4,5])
b.resize(2,3)
print(np.vstack((a,b)))

a=np.array([1,2,3,3,5,4])
a.resize(2,3)
b=np.array([11,22,3,3,4,5])
b.resize(2,3)
print(np.hstack((a,b)))

a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

"""no.of rows become no.of groups
column become rows
group become column

"""

import numpy as np
a1=np.eye(4)
print(a1)

a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

a=np.array([1.3,2.7,3.5,4,5,6,7])
np.rint(a)

a=np.array([7,6,5,4,3,2,1])
b=np.array([1,2,3,4,5,6,7])
np.true_divide(a,b)

a=np.array([1,2,3,3,2,1])
np.unique(a)

a=np.arange(4).reshape(2,2)
b=np.array([[1,2],[7,8]])
np.union1d(a,b)

a=np.arange(4).reshape(2,2)
b=np.array([[1,2],[7,8]])
np.intersect1d(a,b)

a=np.arange(4).reshape(2,2)
b=np.array([[1,2],[7,8]])
np.setdiff1d(a,b)

a=8
b=6
c=np.hypot(a,b)
print(c)

x=np.sin(0)
print(x)

a=np.array([10,21,30,40,50,60])
a=np.array([3,4,2,2,23,25])
print(np.divmod(a,b))

a=np.array([10,21,30,40,50,60])
a=np.array([3,4,2,2,23,25])
print(np.divmod(a,b))

a=np.array([10,21,30,40,50,60])
a=np.array([3,4,2,2,23,25])
print(np.divide(a,b))

a=np.array([1,2,3,4,5,6])
a=np.array([1,2,3,4,5,6])
c=np.multiply(a,b)
print(c)

from numpy import random
x=random.normal(size=(2,3))
print(x)

from numpy import random
x = np.random.normal(loc=1, scale=2, size=(2, 3))
print(x)

x=random.binomial(n=12,p=0.5,size=10)
print(x)

x=random.poisson(lam=2,size=10)
print(x)

a=np.array([1,2,3,4,5,6])
x=random.choice(a)
print(x)

x=random.choice((3,5),p=[0.5,0.5],size=(3,5))
print(x)

