# -*- coding: utf-8 -*-
"""PANDAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRjX3Kk9WTL_XZJ20-AWZVUpieDNamdF
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
a=["vishnu","vardhan","challa","manikanta","dhanush"]
r=pd.Series(a,index=[67,43,44,89,34])
print(r)
df=pd.read_csv("/content/diabetcsv.csv")
print(df)

d=pd.read_csv("/content/grades_withnulls.csv")
print(d)

import pandas as pd
d=pd.read_excel("/content/jai balayya.xlsx")
print(d)

df=pd.read_csv("/content/grades_withnulls.csv")
l1=list(df.columns)
print(l1)

df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.head(7)

df2.isnull().head(7)

df2.isnull().tail(7)

print(df2.isnull().sum())

print(df['SEM1'])

print(df[['SEM1','Names']])

print(df[df.index==1])

print(df[df.index.isin(range(2,5))])

print(df2.loc[3])

print(df2.loc[6:11])

df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5]=None
print(df2)

df2.loc[[10,2,7]]

print(df2.loc[6:11,['Names','Grade',]])

df2.loc[:7,["Names"]]

df2.iloc[10:14,:3]

df2.loc[df['Names']=='Rajesh']

.8,['Names']]df2.loc[df['SEM1']>9

df2[df2.Grade=='A']
df2[df2.SEM2==10]

df3=df2.copy()

print(df3)

df=pd.read_csv("/content/grades_withnulls.csv")

df.dropna(inplace=True,axis=1)
print(df)

df3.dropna(inplace=True,how='all')
print(df3)

mv=df3['SEM2'].mean()
df3=df3.fillna(mv)
print(df3)
print(mv)